version: "2"

services:
  # mongo:
  #   image: mongo
  #   networks:
  #     - my-network
  #   ports:
  #     - "27017:27017"
  #   expose:
  #     - "27017"
  # eureka:
  #   #image: springcloud/eureka # Commented by Dharmendra regarding issue id SCREEN-5, Eureka heartbeat
  #   image: screening/eureka
  #   networks:
  #     - my-network
  #   ports:
  #     - "8761:8761"
  #   expose:
  #     - "8761"
  # redis:
  #   image: redis
  #   networks:
  #     - my-network
  #   ports:
  #     - "6379:6379"
  #   expose:
  #     - "6379"
  # mysql-db:
  #     image: mysql:latest
  #     environment:
  #       - MYSQL_ROOT_PASSWORD=admin123
  #       - MYSQL_USER=dbuser
  #       - MYSQL_PASSWORD=password
  #       - MYSQL_DATABASE=interview
  #     networks:
  #       - my-network
  #     ports:
  #       - "3306:3306"
  #     expose:
  #       - "3306"

  

networks:
  my-network:
    driver: bridge
