#security:

#  oauth2:

#    resource:

#      jwt:

#        key-uri: http://localhost:9999/auth/oauth/token_key

#  basic:

#    enabled: false

#  user:

#    name: admin



eureka:

  client:

    service-url:

      defaultZone: http://localhost:8761/eureka/



eureka:

  client:

    enabled: false



  spring:
 
   datasource:

     url: jdbc:h2:~/test

     username: sa

     password:

     driver-class-name: org.h2.Driver


