#security:

#  oauth2:

#    resource:

#      jwt:

#        key-uri: http://auth.delesio.com:9999/auth/oauth/token_key

#  basic:

#    enabled: false

#  user:

#    name: admin



eureka:
  client:
    service-url:
      defaultZone: http://eureka.techolution.qa:8761/eureka/
  instance:
    hostname: <mongodb_url>
    status-page-url: http://.techolution.com:${server.port}/info
    health-check-url: http://.techolution.com:${server.port}/health
    home-page-url: http://.techolution.com:${server.port}/



  spring: 



